### ISSUE TITLE
void tile

### ISSUE THREAD

**Issue by sebest06** [andrewrk/tmxparser#13]
How do you know when the tile in the map is NULL or is sets with the ID=0?

i think this way

			for (int x = 0; x < layer->GetWidth(); ++x) {
				// If the tile is sets
				if(layer->GetTileTilesetIndex(x, y) != -1){
					// Get the tile's id.
					printf("%03d", layer->GetTileId(x, y));
					// Find a tileset for that id.
					//const Tmx::Tileset *tileset = map->FindTileset(layer->GetTileId(x, y));
					if (layer->IsTileFlippedHorizontally(x, y)){
						printf("h");
					}else{
						printf(" ");
					}
					if (layer->IsTileFlippedVertically(x, y)){
						printf("v");
					}else{
						printf(" ");
					}
					if (layer->IsTileFlippedDiagonally(x, y)){
						printf("d ");
					} else {
						printf("  ");
					}
				}
				else{
					printf("NULL   ");
				}
			}

**Comment by andrewrk** [comment]
Fixed in 53cc3d690c8967851e51143fa6771cb72b7da363
