### ISSUE TITLE
Errors in comments

### ISSUE THREAD

**Issue by georgerbr** [andrewrk/tmxparser#17]
Some classes have errors in the comments that describe them.

In TmxEllipse.h, the description for class Tmx::Ellipse is wrong: "Class to store a Polygon of an Object.". It should be something like: "Class to store an Ellipse of an Object."

In TmxImageLayer.h, the description for class Tmx::ImageLayer is wrong: "A class used for storing information about each of the tilesets...". It should be something like:
"A class used for holding information about a background image.
This class has a property set."

In TmxObjectGroup.h, class Tmx::ObjectGroup *does* have a Tmx::PropertySet properties private member variable, but the class description states that the class doesn't have a property set.

In TmxTileset.h, class Tmx::Tileset *does* have a Tmx::PropertySet properties private member variable, but the class description states that the class doesn't have a property set.

I found these errors while drawing the attached class diagram.
![tmxparser](https://cloud.githubusercontent.com/assets/4930759/5960395/bfa1c57e-a7b3-11e4-834b-802f04dbf204.png)

**Comment by andrewrk** [comment]
fixed in 53cc3d690c8967851e51143fa6771cb72b7da363
