### ISSUE TITLE
undefined reference to `Tmx::Map::ParseText(std::string const&)'

### ISSUE THREAD

**Issue by Wasabi2007** [andrewrk/tmxparser#29]
Hi,
maybe it's only a noob error but I get undefined references to the parse functions.

**What have I done?**

I build tmxparser under Linux with mxe for Mingw 64bit.
Then I copied the resulting Librarys and needed header files into my project.
After that I modified my CmakeLists file to include this:
```
include_directories(tmxparser/include)
link_directories(${CMAKE_CURRENT_SOURCE_DIR}/tmxparser/mingw)
target_link_libraries(Projekt tmxparser tinyxml2 otherlibs )
```
**What have I tried to fix it?**
I tried to use a specific other Library like *libtmxparser.dll.a" and also to change the order in witch tmxparser tinyxml2 and zlib get linked but with no change in result.

Now I don't know further as the example program launches and I don't know what could have been gone wrong with the compiled librarys.

One thing to add, 
yes it get linked because, when I remove the tmxparser from the linking command I get additional  undefined references errors to "Tmx::Map::Map()" and "Tmx::Map::~Map()"

best regards
Wasabi2007

**Comment by Wasabi2007** [comment]
I now build the library with Windows. Now does everything work fine.

Lesson learned.
Don't use mxe for shared libarays.

**Comment by arjanfrans** [comment]
I am having the same problem and I am building on Linux. I am using CMake for my project. It does find the library (`-- Found TMXPARSER: ...`). I tried compiling Tmxparser both as a shared and static library, which didn't make any difference.

Any ideas?

**Comment by Wasabi2007** [comment]
Can you maybe explain more from your build process?
What are the commands you are using?

**Comment by arjanfrans** [comment]
To build tmxparser, I do the following:
```
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
sudo make install
```
This all works fine.

For my project I use `clang` as a compiler and compile c++11 code. Compiler flags I use: ` -Wall -Wextra -Wunused-parameter`.

In my CMake file I do the following to add tmxparser: 
```
find_package(TmxParser REQUIRED)

include_directories(
    ${TMXPARSER_INCLUDE_DIR}
)

add_executable(${PROJECT_NAME}
   main.cpp
   # some more files here.
)

target_link_libraries(
    ${PROJECT_NAME}
    ${TMXPARSER_LIBRARIES}
)
```

I use this to find Tmxparser: https://gist.github.com/arjanfrans/64925384017825e332b3

Here is the code where I am using it:
```
#pragma once

#include <memory>
#include <string>
#include <map>
#include <tmxparser/Tmx.h>

namespace pl {
class ResourceManager {

public:
    Tmx::Map &map(std::string name); // Undefined reference to Tmx::Map

private:
    std::map<std::string, std::unique_ptr<Tmx::Map>> maps;  // Undefined reference to Tmx::Map
};
}
```

**Comment by Wasabi2007** [comment]
So do i see right that you didn't made any of those?
```
make 
make tmxparser
make tmxparser_static
```

because 
```
make install
```
would only copy already compiled files into your central library folder but wouldn't produce any .so .a or .dll file

**Comment by arjanfrans** [comment]
This is indeed my first C++ project :p. Compilation of Tmxparser works fine. It produces the following output:

```
// ... more stuff here
[100%] Built target tmxparser_static
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/include/tmxparser/TmxMapTile.h
-- Installing: /usr/local/include/tmxparser/TmxTile.h
-- Installing: /usr/local/include/tmxparser/TmxTileset.h
-- Installing: /usr/local/include/tmxparser/TmxTileOffset.h
-- Installing: /usr/local/include/tmxparser/TmxEllipse.h
-- Installing: /usr/local/include/tmxparser/TmxObjectGroup.h
-- Installing: /usr/local/include/tmxparser/TmxPolygon.h
-- Installing: /usr/local/include/tmxparser/TmxTerrainArray.h
-- Installing: /usr/local/include/tmxparser/TmxPropertySet.h
-- Installing: /usr/local/include/tmxparser/TmxTileLayer.h
-- Installing: /usr/local/include/tmxparser/TmxImage.h
-- Installing: /usr/local/include/tmxparser/TmxPolyline.h
-- Installing: /usr/local/include/tmxparser/TmxMap.h
-- Installing: /usr/local/include/tmxparser/TmxUtil.h
-- Installing: /usr/local/include/tmxparser/TmxImageLayer.h
-- Installing: /usr/local/include/tmxparser/TmxPoint.h
-- Installing: /usr/local/include/tmxparser/base64.h
-- Installing: /usr/local/include/tmxparser/TmxTerrain.h
-- Installing: /usr/local/include/tmxparser/TmxObject.h
-- Installing: /usr/local/include/tmxparser/TmxLayer.h
-- Installing: /usr/local/include/tmxparser/Tmx.h
-- Installing: /usr/local/lib/libtmxparser.so.2.0.1
-- Installing: /usr/local/lib/libtmxparser.so.2
-- Installing: /usr/local/lib/libtmxparser.so
-- Installing: /usr/local/lib/libtmxparser.a
-- Installing: /usr/local/lib/pkgconfig/tmxparser.pc
```

I am still getting an ` undefined reference to `Tmx::Map::~Map()` when compiling my project. 

I will try to write something minimal and see what happens.

**Comment by Wasabi2007** [comment]
Sorry for the late answer.
Ok simply this answer means that your compiler thinks those Header files are real code it should compiler and link against the .o files from your cpp files. but it doesn't find the corresponding code.

So my gues is that ${TMXPARSER_LIBRARIES} is empty.
try to replace it with
```
tmxparser_static tinyxml zlib
```

**Comment by arjanfrans** [comment]
I just figured it out. Instead of  ${TMXPARSER_LIBRARIES} it is ${TMXPARSER_LIBRARY}

**Comment by Wasabi2007** [comment]
Nice that you found it. 
Than have fun and good luck with your project :)
