### ISSUE TITLE
Crash while loading tmx file

### ISSUE THREAD

**Issue by 3rr3s3v3n** [andrewrk/tmxparser#34]
Hi everyone, I'm using this library with SDL2 to build a simple game on OS X.
When I try to read a tmx file, I got an error code (\x02) with the following message:
"Resources/Map/World3.tmx" where World3.tmx is my map.
What could it be? This is caused only if  launch it from the bundle that Xcode produces.
If I compile my game with a makefile the issue doesn't manifest.
Thank you in advance!

EDIT: It's a tinyXML2 error I think, but I can't figure why..
EDIT2: Solved.

The issue was caused by launching the game from the bundle. The Resources path was altered by the compiler or something like that... Sorry!

**Comment by georgerbr** [comment]
Hi, could you close this issue? Thanks.
