### ISSUE TITLE
Incomplete class

### ISSUE THREAD

**Issue by 3rr3s3v3n** [andrewrk/tmxparser#35]
Hi again.
I'm developing on Xcode, and when I use something like:
```C++
int index = _map.GetTileLayer(k)->GetTile(i,j).id;
```
it doesn't compile anymore because it says:
**Member access into incomplete type 'const Tmx::TileLayer'**
Do you know why?

Thank you in advance!

EDIT: my fault again, something in my .h file went wrong.

**Comment by georgerbr** [comment]
Hi, could you close this issue? Thanks.
