### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by MysticSheik** [andrewrk/tmxparser#37]
I was just wondering if it is possible to compile/build TMXParser on Windows?

**Comment by georgerbr** [comment]
Yes, it is. I myself develop on Windows.

Build with CMake. If that's not your cup of tea, you can always use Visual Studio or Qt Creator (or whatever you like) -- just make sure you have a proper `Tmx.h` (take a look at `src/Tmx.h.in`), get the dependencies, and build. It's that simple.
