### ISSUE TITLE
 How to parse a and display TMX map object in SDL using tmxparser?

### ISSUE THREAD

**Issue by priyanshus1** [andrewrk/tmxparser#38]
Hi,
I am newbie in this field getting too much trouble in simple platform game for one of my project module
if you guys could help or share some code. This is what I have done till now.

I could parse a Tmx Map (created using tiled map editor)and display it using TmxParser library, But I don't know how to handle Map Object , Although I could get on internet how to parse also used an example given in the library it self. But I am not good at programming I would like to share code.

Objective : To make a simple Platform game where player can move and jump
Tools to be used : C++, Tiled , tmxparser and SDL

please help thanks in advance!
here is my code
please help 
[test.zip](https://github.com/andrewrk/tmxparser/files/66443/test.zip)

**Comment by georgerbr** [comment]
Making a platform game is just too complex for a beginner. Read [this](http://www.gamedev.net/page/resources/_/technical/game-programming/your-first-step-to-game-development-starts-here-r2976), [this](http://www.gamefromscratch.com/post/2013/08/01/Just-starting-out-what-games-should-I-make.aspx), and [this](http://web.archive.org/web/20051104034215/http://www.lupinegames.com/articles/path_to_dev.html).

If that didn't change your mind, then do [all of these](http://lazyfoo.net/tutorials/SDL/index.php) up to Lesson 39 - Tiling, and try your hand at retrofitting the code to use tmxparser.

**Comment by priyanshus1** [comment]
Thanks for reply but I really not a beginner I know SDL programming I am
just facing problem in accessing a MapObject and render it using SDL if you
could share some example code of rendering one MapObject I can do the rest.
Thanks in Advance :)

On Saturday 19 December 2015, Georger Araújo <notifications@github.com>
wrote:

> Making a platform game is just too complex for a beginner. Read this
> <http://www.gamedev.net/page/resources/_/technical/game-programming/your-first-step-to-game-development-starts-here-r2976>,
> this
> <http://www.gamefromscratch.com/post/2013/08/01/Just-starting-out-what-games-should-I-make.aspx>,
> and this
> <http://web.archive.org/web/20051104034215/http://www.lupinegames.com/articles/path_to_dev.html>
> .
>
> If that didn't change your mind, then do all of these
> <http://lazyfoo.net/tutorials/SDL/index.php> up to Lesson 39 - Tiling,
> and try your hand at retrofitting the code to use tmxparser.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andrewrk/tmxparser/issues/38#issuecomment-165920662>.
>


-- 

*Regards    Priyanshu Shukla                            *

*Student       *

*Department of Computer Engineering       Pune Institute of Computer
Technology   *


*India                                 *
PS: To reach please mail at priyanshus1@gmail.com or call +91-90280-80386

**Comment by georgerbr** [comment]
I downloaded and read your code, and to me it looks like code a beginner would write.

Sorry for being blunt, but I don't think you want to share code; rather I think you want someone to give working code to you -- if that's the case, there's [a project](https://github.com/fallahn/sfml-tmxloader) that does just that, albeit with SFML rather than SDL.

A final note: if you're serious about being a developer, work on your problem solving skills.

**Comment by priyanshus1** [comment]
Dear George,
Sorry about asking dumb questions, yes I wanted code but not complete, I
wanted something like a template or tutorial. Because for a beginner
programmer it is difficult to read the library and use it by own , That's
why I requested for the code (template code),
Library which you have shared does not uses SDL that is what I am seeing
right now, but I am using SDL2.0 for rest of my work that's why I was
requesting you  for the code. Can you help me more? Can I speak to you on
Google Hangouts/Skype if possible.
Thanks in Advance ! :)


*Regards    Priyanshu Shukla                            *

*Student       *

*Department of Computer Engineering       Pune Institute of Computer
Technology   *


*India                                 *
PS: To reach please mail at priyanshus1@gmail.com or call +91-90280-80386

**Comment by priyanshus1** [comment]
Hi all after digging up I solved the problem 
Thanks for your support 
Admin can close this issue
