### ISSUE TITLE
Wrong Tile gid

### ISSUE THREAD

**Issue by andrewrk** [andrewrk/tmxparser#4]
Hello, 
I am trying to display the ID of my tiles using the Tmx::Layer::Gettile method. However the ID returned is not correct. I am using several tilesets, and the ID returned is actually the correct one minus the firstgid of the tileset.
For example, I expect to see the tile ID 129, but 32 appears (because the firstgid of the tileset is 97). This is a problem when I call the FindTileSet method as the ID is wrong.

I did find the line of code that causes the problem. It is in the TmxMapTile.h file, in the 
MapTile(unsigned _gid, int _tilesetFirstGid, unsigned _tilesetId)
constructor, you write: 
id -= _tilesetFirstGid;

Removing this line solves my problem. My question is, what is the purpose of this line in the first place ? It causes the wrong reading of tile IDs when using several Tilesets.
Thanks, 
Pierre

**Comment by Galbar** [comment]
This is solved in #20 .
